name: Build checks

on: [push, pull_request]

jobs:
  build-tarball:
    name: Build tarball from GIT
    runs-on: ubuntu-20.04
    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends libltdl-dev libcairo2-dev libx11-dev libxml2-dev libxml2-utils libncurses5-dev libxnvctrl-dev libpciaccess-dev libudev-dev pkg-config ocl-icd-opencl-dev autoconf automake libtool doxygen-latex transfig
    - uses: actions/checkout@v4
    - name: Autogen
      run: ./autogen.sh
    - name: Configure
      run: ./configure --prefix=${PWD}/install
    - name: Build
      run: make -j
    - name: Distcheck
      run: make distcheck
    - name: Check versions
      run: |
        contrib/windows/check-versions.sh
        contrib/windows-cmake/check-versions.sh
        contrib/android/check-versions.sh
    - name: Archive tarballs
      uses: actions/upload-artifact@v3
      with:
        name: Tarball
        path: hwloc-*.tar.gz
    - name: Archive documentation PDF
      uses: actions/upload-artifact@v3
      with:
        name: Documentation PDF
        path: doc/doxygen-doc/hwloc-a4.pdf
  check-tarball-gh-ubuntu-latest:
    name: Check tarball on GH ubuntu-latest
    needs: build-tarball
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y --no-install-recommends pkg-config libcairo2-dev libxml2-dev
    - name: Download tarball
      uses: actions/download-artifact@v3
      with:
        name: Tarball
    - name: Extract
      run: tar xvf hwloc-*.tar.gz
  check-tarball-gh-macos-latest:
    name: Check tarball on GH macosx-latest
    needs: build-tarball
    runs-on: macosx-latest
    steps:
    - name: Install dependencies
      run: |
        brew install pkg-config
        brew install cairo
    - name: Download tarball
      uses: actions/download-artifact@v3
      with:
        name: Tarball
    - name: Extract
      run: tar xvf hwloc-*.tar.gz
# check-tarball:
#   name: Check tarball on GH runners
#   needs: build-tarball
#    strategy:
#      matrix:
#        os: [ubuntu-latest,macos-latest]
#   runs-on: ${{ matrix.os }}
#   steps:
#   - name: Download tarball
#     uses: actions/download-artifact@v3
#     with:
#       name: Tarball
#   - name: Extract
#     run: tar xvf hwloc-*.tar.gz
